server:
  port: 8080

spring:
  application:
    name: otp_simple_project
  datasource:
    url: jdbc:h2:mem:sampledb
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
    show-sql: true
    ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  mail:
    host: "${SMTP_HOST:localhost}"
    port: "${SMTP_PORT:1025}"
    username: "${EMAIL_USERNAME:admin@mail.me}"
    password: "${EMAIL_PASSWORD:admin}"
    test-connection: false
    properties:
      health:
        mail:
          enabled: false
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true

notification:
  smpp:
    host: "${SMPP_HOST:localhost}"
    port: "${SMPP_PORT:2775}"
    system_id: "${SMPP_SYSTEM_ID:smppclient1}"
    password: "${SMPP_PASSWORD:password}"
    system_type: "OTP"
    source_addr: "OTPService"
  telegram:
    bot:
      token: "${TELEGRAM_BOT_TOKEN:}"

management:
  endpoints:
    web:
      exposure:
        include: health

security:
  token:
    signing:
      key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
    expiration:
      milliseconds: 144000000

role:
  admin:
    list: "Viktor,admin,root"

